workflows:
  ios-release:
    name: iOS Release Build
    environment:
      vars:
        XCODE_PROJECT: "SmartKurv.xcodeproj"
        XCODE_SCHEME: "SmartKurv"
        APP_STORE_CONNECT_TEAM_ID: "GUYJ52Y55V"   # <-- sæt dit eget Team ID
      xcode: latest
      cocoapods: default
      node: latest

    scripts:
      # 1️⃣ Install dependencies
      - name: Install dependencies
        script: |
          set -euxo pipefail
          gem install cocoapods
          pod install

      # 2️⃣ Regenerate Xcode project (via XcodeGen)
      - name: Regenerate project
        script: |
          set -euxo pipefail
          xcodegen generate

      # 3️⃣ Verify that Assets.xcassets exists
      - name: Verify assets presence
        script: |
          set -euxo pipefail
          echo "== Checking for Assets.xcassets/AppIcon.appiconset =="
          if [ ! -d "Assets.xcassets/AppIcon.appiconset" ]; then
            echo "❌ AppIcon.appiconset missing!"
            exit 1
          fi
          ls -la Assets.xcassets/AppIcon.appiconset

      # 4️⃣ Ensure Info.plist contains CFBundleIconName
      - name: Ensure CFBundleIconName exists
        script: |
          set -euxo pipefail
          PLIST="Info.plist"
          if /usr/libexec/PlistBuddy -c "Print :CFBundleIconName" "$PLIST" >/dev/null 2>&1; then
            echo "✅ CFBundleIconName already present"
          else
            echo "🔧 Adding CFBundleIconName = AppIcon"
            /usr/libexec/PlistBuddy -c "Add :CFBundleIconName string AppIcon" "$PLIST"
          fi
          echo "== Info.plist keys =="
          /usr/libexec/PlistBuddy -c "Print :CFBundleIconName" "$PLIST"
          /usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "$PLIST" || true
          /usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "$PLIST" || true

      # 5️⃣ Build & archive
      - name: Build and archive
        script: |
          set -euxo pipefail
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath "$CM_BUILD_DIR/SmartKurv.xcarchive" \
            -sdk iphoneos \
            -allowProvisioningUpdates \
            DEVELOPMENT_TEAM="$APP_STORE_CONNECT_TEAM_ID" \
            ASSETCATALOG_COMPILER_APPICON_NAME=AppIcon \
            archive

      # 6️⃣ Verify archive Info.plist
      - name: Verify archive Info.plist
        script: |
          set -euxo pipefail
          APP_PLIST="$CM_BUILD_DIR/SmartKurv.xcarchive/Products/Applications/SmartKurv.app/Info.plist"
          echo "== CFBundleIconName in archive =="
          /usr/libexec/PlistBuddy -c "Print :CFBundleIconName" "$APP_PLIST" || echo "❌ Missing CFBundleIconName!"
          ls -la "$CM_BUILD_DIR/SmartKurv.xcarchive/Products/Applications/SmartKurv.app" | grep -i appicon || true

      # 7️⃣ Export IPA
      - name: Export IPA
        script: |
          set -euxo pipefail
          xcodebuild \
            -exportArchive \
            -archivePath "$CM_BUILD_DIR/SmartKurv.xcarchive" \
            -exportOptionsPlist "ExportOptions.plist" \
            -exportPath "$CM_BUILD_DIR/exported"

      # 8️⃣ Upload to TestFlight / App Store
      - name: Upload to App Store Connect
        script: |
          set -euxo pipefail
          app-store-connect publish \
            --apple-id 6753662256 \
            --path "$CM_BUILD_DIR/exported/SmartKurv.ipa"

    artifacts:
      - "$CM_BUILD_DIR/exported/SmartKurv.ipa"
