workflows:
  ios_release:
    name: SmartKurv iOS (TestFlight)
    environment:
      xcode: latest
      groups:
        - smartkurv   # APP_STORE_CONNECT_ISSUER_ID, APP_STORE_CONNECT_KEY_IDENTIFIER, APP_STORE_CONNECT_PRIVATE_KEY, P12_PASSWORD
      vars:
        APP_BUNDLE_ID: com.youssef19900.SmartKurv
        TEAM_ID: GUYJ52Y55V
        APPLE_APP_ID: "6753662256"

    scripts:
      - name: "Install tools"
        script: |
          set -euxo pipefail
          brew install xcodegen
          pip3 install --upgrade codemagic-cli-tools

      - name: "Regenerate project (fresh)"
        script: |
          set -euxo pipefail
          rm -rf SmartKurv.xcodeproj
          xcodegen generate --spec project.yml

      - name: "Reset signing keys inside .xcodeproj (aggressive)"
        script: |
          set -euxo pipefail
          PBX="SmartKurv.xcodeproj/project.pbxproj"
          cp "$PBX" "$PBX.bak" || true
          /usr/bin/sed -i '' -e 's/Apple Distribution: [^"]*/Apple Distribution/g' "$PBX"
          /usr/bin/sed -i '' \
            -e 's/PROVISIONING_PROFILE_SPECIFIER = "[^"]*";/PROVISIONING_PROFILE_SPECIFIER = "";/g' \
            -e 's/PROVISIONING_PROFILE = "[^"]*";/PROVISIONING_PROFILE = "";/g' \
            "$PBX"
          /usr/bin/sed -i '' -e 's/CODE_SIGN_STYLE = Automatic;/CODE_SIGN_STYLE = Manual;/g' "$PBX"
          grep -E 'CODE_SIGN_STYLE|CODE_SIGN_IDENTITY|PROVISIONING_PROFILE' "$PBX" || true

      - name: "Guard - no old cert CNs remain"
        script: |
          set -euxo pipefail
          if grep -n 'Apple Distribution:' SmartKurv.xcodeproj/project.pbxproj | grep -v 'CODE_SIGN_IDENTITY = "Apple Distribution";' ; then
            echo "Found a named Apple Distribution CN in project file. Stopping."
            grep -n 'Apple Distribution:' SmartKurv.xcodeproj/project.pbxproj || true
            exit 1
          fi

      - name: "Generate CSR key & fetch signing files (to known folder)"
        script: |
          set -euo pipefail
          SIGNING_DIR="$CM_BUILD_DIR/signing"
          mkdir -p "$SIGNING_DIR"

          CERT_KEY_PATH="$SIGNING_DIR/cert_key.pem"
          openssl genrsa -out "$CERT_KEY_PATH" 2048
          test -s "$CERT_KEY_PATH"

          set +x
          CERT_KEY_CONTENT="$(cat "$CERT_KEY_PATH")"
          set -x

          app-store-connect fetch-signing-files \
            "$APP_BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create \
            --delete-stale-profiles \
            --certificate-key "$CERT_KEY_CONTENT" \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY" \
            --p12-password "$P12_PASSWORD" \
            --output-directory "$SIGNING_DIR"

          echo "== Listing fetched files =="
          ls -la "$SIGNING_DIR" || true
          # fjern nøglefil efter brug
          rm -f "$CERT_KEY_PATH"

      - name: "Import certs & apply profiles"
        script: |
          set -euxo pipefail
          SIGNING_DIR="$CM_BUILD_DIR/signing"
          keychain initialize
          # Importer præcis den .p12 vi lige hentede
          keychain add-certificates --certificate "$SIGNING_DIR"/*.p12 --certificate-password "$P12_PASSWORD"
          # Brug de profiler, der ligger i samme mappe
          xcode-project use-profiles --project SmartKurv.xcodeproj --profiles "$SIGNING_DIR"

      - name: "Diagnose signing state"
        script: |
          set -euxo pipefail
          echo "== Keychain identities =="
          security find-identity -p codesigning -v || true
          echo "== Build settings (excerpt) =="
          xcodebuild -project SmartKurv.xcodeproj -scheme SmartKurv -showBuildSettings | \
            grep -E 'CODE_SIGN_STYLE|DEVELOPMENT_TEAM|PRODUCT_BUNDLE_IDENTIFIER|PROVISIONING_PROFILE_SPECIFIER|CODE_SIGN_IDENTITY' || true

      - name: "Build archive (codesigned)"
        script: |
          set -euxo pipefail
          xcodebuild \
            -project SmartKurv.xcodeproj \
            -scheme SmartKurv \
            -configuration Release \
            -archivePath "$CM_BUILD_DIR/SmartKurv.xcarchive" \
            -sdk iphoneos \
            -allowProvisioningUpdates \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            DEVELOPMENT_TEAM="$TEAM_ID" \
            archive

      - name: "Write exportOptions.plist (App Store)"
        script: |
          set -euxo pipefail
          cat > "$CM_BUILD_DIR/exportOptions.plist" << 'PLIST'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store</string>
            <key>uploadSymbols</key><true/>
            <key>compileBitcode</key><false/>
            <key>destination</key><string>export</string>
          </dict>
          </plist>
          PLIST

      - name: "Export .ipa"
        script: |
          set -euxo pipefail
          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/SmartKurv.xcarchive" \
            -exportOptionsPlist "$CM_BUILD_DIR/exportOptions.plist" \
            -exportPath "$CM_BUILD_DIR/exported"

      - name: "Publish to TestFlight"
        script: |
          set -euxo pipefail
          app-store-connect publish \
            --apple-id "$APPLE_APP_ID" \
            --path "$CM_BUILD_DIR/exported/SmartKurv.ipa"

    artifacts:
      - "$CM_BUILD_DIR/exported/*.ipa"
