workflows:
  ios_release:
    name: SmartKurv iOS (TestFlight)
    environment:
      xcode: latest
      groups:
        - smartkurv            # Henter dine env-vars fra denne gruppe
      vars:
        APP_BUNDLE_ID: com.youssef19900.SmartKurv
        TEAM_ID: GUYJ52Y55V

    scripts:
      - name: Install tools
        script: |
          set -euxo pipefail
          brew install xcodegen
          pip3 install --upgrade codemagic-cli-tools

      - name: Generate Xcode project
        script: |
          set -euxo pipefail
          xcodegen generate --spec project.yml

      - name: Fetch signing files (cert+profiles) from App Store Connect
        script: |
          set -euxo pipefail
          # Hurtig sanity-check at variabler er indlæst:
          test -n "$ASC_ISSUER_ID" && echo "ISSUER_ID OK"
          test -n "$ASC_KEY_ID" && echo "KEY_ID OK"
          test -n "$ASC_PRIVATE_KEY" && echo "PRIVATE_KEY length: $(printf %s "$ASC_PRIVATE_KEY" | wc -c)"
          app-store-connect fetch-signing-files \
            --issuer-id "$ASC_ISSUER_ID" \
            --key-id "$ASC_KEY_ID" \
            --private-key "$ASC_PRIVATE_KEY" \
            --app-identifier "$APP_BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create

      - name: Import certs & apply profiles to Xcode project
        script: |
          set -euxo pipefail
          keychain initialize
          keychain add-certificates
          xcode-project use-profiles \
            --project SmartKurv.xcodeproj \
            --target SmartKurv

      - name: Build archive (codesigned)
        script: |
          set -euxo pipefail
          xcodebuild \
            -project SmartKurv.xcodeproj \
            -scheme SmartKurv \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/SmartKurv.xcarchive \
            -sdk iphoneos \
            -allowProvisioningUpdates \
            archive

      - name: Write exportOptions.plist (App Store)
        script: |
          set -euxo pipefail
          cat > $CM_BUILD_DIR/exportOptions.plist << 'PLIST'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store</string>
            <key>uploadSymbols</key><true/>
            <key>compileBitcode</key><false/>
            <key>destination</key><string>export</string>
          </dict>
          </plist>
          PLIST
          cat $CM_BUILD_DIR/exportOptions.plist

      - name: Export .ipa
        script: |
          set -euxo pipefail
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/SmartKurv.xcarchive \
            -exportOptionsPlist $CM_BUILD_DIR/exportOptions.plist \
            -exportPath $CM_BUILD_DIR/exported

      - name: Publish to TestFlight
        script: |
          set -euxo pipefail
          app-store-connect publish \
            --issuer-id "$ASC_ISSUER_ID" \
            --key-id "$ASC_KEY_ID" \
            --private-key "$ASC_PRIVATE_KEY" \
            --path "$CM_BUILD_DIR/exported/SmartKurv.ipa" \
            --bundle-id "$APP_BUNDLE_ID" \
            --apple-id "$APPLE_APP_ID"

    artifacts:
      - $CM_BUILD_DIR/exported/*.ipa
      - $CM_BUILD_DIR/SmartKurv.xcarchive
