workflows:
  ios_build:
    name: SmartKurv iOS build
    environment:
      xcode: latest
    scripts:
      - name: Install XcodeGen
        script: |
          set -euxo pipefail
          brew install xcodegen
      - name: Generate Xcode project
        script: |
          set -euxo pipefail
          xcodegen generate --spec project.yml
          test -d SmartKurv.xcodeproj
          ls -la
      - name: Build archive (no codesign)
        script: |
          set -euxo pipefail
          xcodebuild \
            -project SmartKurv.xcodeproj \
            -scheme SmartKurv \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/SmartKurv.xcarchive \
            -sdk iphoneos \
            archive CODE_SIGNING_ALLOWED=NO
      - name: Write exportOptions.plist
        script: |
          set -euxo pipefail
          cat > $CM_BUILD_DIR/exportOptions.plist << 'PLIST'
          {
            "method": "ad-hoc",
            "compileBitcode": false,
            "signingStyle": "manual",
            "stripSwiftSymbols": true
          }
          PLIST
          cat $CM_BUILD_DIR/exportOptions.plist
      - name: Export .ipa (unsigned)
        script: |
          set -euxo pipefail
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/SmartKurv.xcarchive \
            -exportOptionsPlist $CM_BUILD_DIR/exportOptions.plist \
            -exportPath $CM_BUILD_DIR/exported
    artifacts:
      - $CM_BUILD_DIR/exported/*.ipa
