workflows:
  ios_release:
    name: SmartKurv iOS (TestFlight)
    environment:
      xcode: latest
      groups:
        - smartkurv    # Skal indeholde: APP_STORE_CONNECT_ISSUER_ID, APP_STORE_CONNECT_KEY_IDENTIFIER, APP_STORE_CONNECT_PRIVATE_KEY, P12_PASSWORD (m.fl.)
      vars:
        APP_BUNDLE_ID: com.youssef19900.SmartKurv
        TEAM_ID: GUYJ52Y55V
        APPLE_APP_ID: "6753662256"

    scripts:
      - name: Install tools
        script: |
          set -euxo pipefail
          brew install xcodegen
          pip3 install --upgrade codemagic-cli-tools

      - name: Regenerate project (fresh)
        script: |
          set -euxo pipefail
          rm -rf SmartKurv.xcodeproj
          xcodegen generate --spec project.yml

      - name: Reset signing keys inside .xcodeproj
        script: |
          set -euxo pipefail
          PBX="SmartKurv.xcodeproj/project.pbxproj"
          cp "$PBX" "$PBX.bak" || true
          /usr/bin/sed -i '' \
            -e 's/CODE_SIGN_IDENTITY = "Apple Distribution: [^"]*";/CODE_SIGN_IDENTITY = "Apple Distribution";/g' \
            -e 's/CODE_SIGN_IDENTITY\[sdk=iphoneos\*\] = "Apple Distribution: [^"]*";/CODE_SIGN_IDENTITY\[sdk=iphoneos\*\] = "Apple Distribution";/g' \
            -e 's/PROVISIONING_PROFILE_SPECIFIER = "[^"]*";/PROVISIONING_PROFILE_SPECIFIER = "";/g' \
            -e 's/PROVISIONING_PROFILE = "[^"]*";/PROVISIONING_PROFILE = "";/g' \
            "$PBX" || true
          grep -E 'CODE_SIGN_STYLE|CODE_SIGN_IDENTITY|PROVISIONING_PROFILE' "$PBX" || true

      - name: Generate CSR key & fetch signing files
        script: |
          set -euo pipefail

          CERT_KEY_PATH="$CM_BUILD_DIR/cert_key.pem"
          # Generér midlertidig key til CSR
          openssl genrsa -out "$CERT_KEY_PATH" 2048
          test -s "$CERT_KEY_PATH"

          # Undgå at nøgleindhold ender i log (slå xtrace fra, slå til igen bagefter)
          set +x
          CERT_KEY_CONTENT="$(cat "$CERT_KEY_PATH")"
          set -x

          app-store-connect fetch-signing-files \
            "$APP_BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create \
            --delete-stale-profiles \
            --certificate-key "$CERT_KEY_CONTENT" \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY" \
            --p12-password "$P12_PASSWORD"

          # Ryd op
          rm -f "$CERT_KEY_PATH"

      - name: Import certs & apply profiles
        script: |
          set -euxo pipefail
          keychain initialize
          keychain add-certificates --certificate-password "$P12_PASSWORD"
          xcode-project use-profiles --project SmartKurv.xcodeproj

      - name: Diagnose signing state
        script: |
          set -euxo pipefail
          echo "== Keychain identities =="
          security find-identity -p codesigning -v || true
          echo "== Build settings (uddrag) =="
          xcodebuild -project SmartKurv.xcodeproj -scheme SmartKurv -showBuildSettings | \
            grep -E 'CODE_SIGN_STYLE|DEVELOPMENT_TEAM|PRODUCT_BUNDLE_IDENTIFIER|PROVISIONING_PROFILE_SPECIFIER|CODE_SIGN_IDENTITY' || true

      - name: Build archive (codesigned)
        script: |
          set -euxo pipefail
          xcodebuild \
            -project SmartKurv.xcodeproj \
            -scheme SmartKurv \
            -configuration Release \
            -archivePath "$CM_BUILD_DIR/SmartKurv.xcarchive" \
            -sdk iphoneos \
            -allowProvisioningUpdates \
            archive

      - name: Write exportOptions.plist (App Store)
        script: |
          set -euxo pipefail
          cat > "$CM_BUILD_DIR/exportOptions.plist" << 'PLIST'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store</string>
            <key>uploadSymbols</key><true/>
            <key>compileBitcode</key><false/>
            <key>destination</key><string>export</string>
          </dict>
          </plist>
          PLIST

      - name: Export .ipa
        script: |
          set -euxo pipefail
          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/SmartKurv.xcarchive" \
            -exportOptionsPlist "$CM_BUILD_DIR/exportOptions.plist" \
            -exportPath "$CM_BUILD_DIR/exported"

      - name: Publish to TestFlight
        script: |
          set -euxo pipefail
          app-store-connect publish \
            --apple-id "$APPLE_APP_ID" \
            --path "$CM_BUILD_DIR/exported/SmartKurv.ipa"

    artifacts:
      - "$CM_BUILD_DIR/exported/*.ipa"
