workflows:
  ios_release:
    name: SmartKurv iOS (TestFlight)
    environment:
      xcode: latest
      groups:
        - smartkurv   # Skal indeholde: P12_BASE64, P12_PASSWORD, PROFILE_BASE64, APP_STORE_CONNECT_ISSUER_ID, APP_STORE_CONNECT_KEY_IDENTIFIER, APP_STORE_CONNECT_PRIVATE_KEY
      vars:
        APP_BUNDLE_ID: com.youssef19900.SmartKurv
        TEAM_ID: GUYJ52Y55V
        APPLE_APP_ID: "6753662256"
        ICON_SET_PATH: Smartkurv/Assets.xcassets/AppIcon.appiconset

    scripts:
      - name: Install tools
        script: |
          set -euxo pipefail
          brew install xcodegen
          pip3 install --upgrade codemagic-cli-tools

      - name: Regenerate project (fresh)
        script: |
          set -euxo pipefail
          rm -rf SmartKurv.xcodeproj
          xcodegen generate --spec project.yml

      - name: Quick sanity (assets + build settings)
        script: |
          set -euxo pipefail
          echo "== Assets directory (root) =="
          ls -la Smartkurv/Assets.xcassets || true
          echo "== AppIcon set =="
          ls -la "$ICON_SET_PATH" || true
          echo "Contents.json:"
          cat "$ICON_SET_PATH/Contents.json" || true
          echo "== Build settings (excerpt) =="
          xcodebuild -project SmartKurv.xcodeproj -scheme SmartKurv -showBuildSettings | \
            grep -Ei 'ASSETCATALOG|ICON|INFOPLIST_FILE|PRODUCT_BUNDLE_IDENTIFIER' || true

      - name: Validate AppIcon sizes
        script: |
          set -euxo pipefail
          cd "$ICON_SET_PATH"
          for f in AppIcon-60@2x.png AppIcon-60@3x.png AppIcon-1024.png; do
            test -f "$f" || { echo "Mangler $f"; exit 1; }
          done
          W2=$(sips -g pixelWidth  AppIcon-60@2x.png | awk '/pixelWidth/ {print $2}')
          H2=$(sips -g pixelHeight AppIcon-60@2x.png | awk '/pixelHeight/ {print $2}')
          W3=$(sips -g pixelWidth  AppIcon-60@3x.png | awk '/pixelWidth/ {print $2}')
          H3=$(sips -g pixelHeight AppIcon-60@3x.png | awk '/pixelHeight/ {print $2}')
          WM=$(sips -g pixelWidth  AppIcon-1024.png  | awk '/pixelWidth/ {print $2}')
          HM=$(sips -g pixelHeight AppIcon-1024.png  | awk '/pixelHeight/ {print $2}')
          [ "$W2" = "120" ] && [ "$H2" = "120" ] || { echo "AppIcon-60@2x.png skal være 120x120"; exit 1; }
          [ "$W3" = "180" ] && [ "$H3" = "180" ] || { echo "AppIcon-60@3x.png skal være 180x180"; exit 1; }
          [ "$WM" = "1024" ] && [ "$HM" = "1024" ] || { echo "AppIcon-1024.png skal være 1024x1024"; exit 1; }

      - name: Remove alpha on 1024 (marketing)
        script: |
          set -euxo pipefail
          cd "$ICON_SET_PATH"
          HAS_ALPHA=$(sips -g hasAlpha AppIcon-1024.png | awk '/hasAlpha/ {print $2}')
          if [ "$HAS_ALPHA" = "yes" ]; then
            brew install imagemagick
            magick AppIcon-1024.png -background white -alpha remove -alpha off AppIcon-1024.png
            echo "Alpha fjernet fra AppIcon-1024.png"
            sips -g hasAlpha AppIcon-1024.png
          fi

      - name: Import .p12 certificate
        script: |
          set -euxo pipefail
          keychain initialize
          echo "$P12_BASE64" | base64 --decode > "$CM_BUILD_DIR/AppleDistribution.p12"
          keychain add-certificates --certificate "$CM_BUILD_DIR/AppleDistribution.p12" --certificate-password "$P12_PASSWORD"
          security find-identity -p codesigning -v || true

      - name: Restore provisioning profile (to standard folder)
        script: |
          set -euxo pipefail
          STD_DIR="$HOME/Library/MobileDevice/Provisioning Profiles"
          mkdir -p "$STD_DIR"
          PROFILE_STD="$STD_DIR/SmartKurv_AppStore.mobileprovision"
          echo "$PROFILE_BASE64" | base64 --decode > "$PROFILE_STD"
          test -s "$PROFILE_STD"

      - name: Configure signing in Xcode project
        script: |
          set -euxo pipefail
          PBX="SmartKurv.xcodeproj/project.pbxproj"
          sed -i '' -e 's/CODE_SIGN_STYLE = Automatic;/CODE_SIGN_STYLE = Manual;/g' "$PBX" || true
          sed -i '' -e 's/PROVISIONING_PROFILE_SPECIFIER = "[^"]*";/PROVISIONING_PROFILE_SPECIFIER = "";/g' "$PBX" || true
          sed -i '' -e 's/PROVISIONING_PROFILE = "[^"]*";/PROVISIONING_PROFILE = "";/g' "$PBX" || true
          xcode-project use-profiles --project SmartKurv.xcodeproj

      - name: Bump version & build (ensure)
        script: |
          set -euxo pipefail
          PLIST="Info.plist"
          /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString 1.1" "$PLIST" || \
            /usr/libexec/PlistBuddy -c "Add :CFBundleShortVersionString string 1.1" "$PLIST"
          BUILD_NUM="$(date +%Y%m%d%H%M)"
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion ${BUILD_NUM}" "$PLIST" || \
            /usr/libexec/PlistBuddy -c "Add :CFBundleVersion string ${BUILD_NUM}" "$PLIST"
          /usr/libexec/PlistBuddy -c "Set :CFBundleIconName AppIcon" "$PLIST" || \
            /usr/libexec/PlistBuddy -c "Add :CFBundleIconName string AppIcon" "$PLIST"

      - name: Build archive (codesigned)
        script: |
          set -euxo pipefail
          xcodebuild \
            -project SmartKurv.xcodeproj \
            -scheme SmartKurv \
            -configuration Release \
            -archivePath "$CM_BUILD_DIR/SmartKurv.xcarchive" \
            -sdk iphoneos \
            -allowProvisioningUpdates \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            DEVELOPMENT_TEAM="$TEAM_ID" \
            archive

      - name: Inspect Assets.car for icons (debug only)
        script: |
          set -euxo pipefail
          APP_PATH="$CM_BUILD_DIR/SmartKurv.xcarchive/Products/Applications/SmartKurv.app"
          if [ -f "$APP_PATH/Assets.car" ]; then
            ls -la "$APP_PATH/Assets.car"
            /usr/bin/assetutil --info "$APP_PATH/Assets.car" | head -n 200 || true
          else
            echo "⚠️ Ingen Assets.car i appen – tjek at project.yml resources peger på 'Smartkurv/Assets.xcassets'."
            ls -la "$APP_PATH" || true
          fi

      - name: Detect profile name & Write exportOptions.plist
        script: |
          set -euxo pipefail
          PROFILE_STD="$HOME/Library/MobileDevice/Provisioning Profiles/SmartKurv_AppStore.mobileprovision"
          PROFILE_PLIST="$CM_BUILD_DIR/profile.plist"
          /usr/bin/security cms -D -i "$PROFILE_STD" > "$PROFILE_PLIST"
          PROFILE_NAME=$(/usr/libexec/PlistBuddy -c 'Print :Name' "$PROFILE_PLIST")
          cat > "$CM_BUILD_DIR/exportOptions.plist" << PLIST
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store</string>
            <key>teamID</key><string>$TEAM_ID</string>
            <key>signingStyle</key><string>manual</string>
            <key>signingCertificate</key><string>Apple Distribution</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>$APP_BUNDLE_ID</key>
              <string>$PROFILE_NAME</string>
            </dict>
            <key>uploadSymbols</key><true/>
            <key>compileBitcode</key><false/>
            <key>destination</key><string>export</string>
          </dict>
          </plist>
          PLIST

      - name: Export .ipa
        script: |
          set -euxo pipefail
          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/SmartKurv.xcarchive" \
            -exportOptionsPlist "$CM_BUILD_DIR/exportOptions.plist" \
            -exportPath "$CM_BUILD_DIR/exported"

      - name: Upload to TestFlight
        script: |
          set -euxo pipefail
          app-store-connect publish \
            --apple-id "$APPLE_APP_ID" \
            --path "$CM_BUILD_DIR/exported/SmartKurv.ipa"

    artifacts:
      - "$CM_BUILD_DIR/exported/*.ipa"
