workflows:
  ios_release:
    name: "SmartKurv iOS (TestFlight)"
    environment:
      xcode: latest
      groups:
        - smartkurv
      vars:
        APP_BUNDLE_ID: com.youssef19900.SmartKurv
        TEAM_ID: GUYJ52Y55V
        APPLE_APP_ID: "6753662256"

    scripts:
      - name: "Install tools"
        script: |
          set -euxo pipefail
          brew install xcodegen
          pip3 install --upgrade codemagic-cli-tools

      - name: "Regenerate project fresh"
        script: |
          set -euxo pipefail
          rm -rf SmartKurv.xcodeproj
          xcodegen generate --spec project.yml

      - name: "Verify AppIcon presence"
        script: |
          set -euxo pipefail
          echo "== Checking for Assets.xcassets/AppIcon.appiconset =="
          APPICON_DIR="Assets.xcassets/AppIcon.appiconset"
          test -d "$APPICON_DIR"
          ls -la "$APPICON_DIR"
          for f in AppIcon-60@2x.png AppIcon-60@3x.png AppIcon-1024.png; do
            if [ ! -f "$APPICON_DIR/$f" ]; then
              echo "Missing $f in AppIcon.appiconset"
              exit 1
            fi
          done
          echo "AppIcon files found"

      - name: "Normalize Contents json to AppIcon filenames"
        script: |
          set -euxo pipefail
          APPICON_DIR="Assets.xcassets/AppIcon.appiconset"
          mkdir -p "$APPICON_DIR"
          cat > "$APPICON_DIR/Contents.json" <<'JSON'
          {
            "images": [
              { "size": "20x20",    "idiom": "iphone",         "filename": "AppIcon-20@2x.png",   "scale": "2x" },
              { "size": "20x20",    "idiom": "iphone",         "filename": "AppIcon-20@3x.png",   "scale": "3x" },
              { "size": "29x29",    "idiom": "iphone",         "filename": "AppIcon-29@2x.png",   "scale": "2x" },
              { "size": "29x29",    "idiom": "iphone",         "filename": "AppIcon-29@3x.png",   "scale": "3x" },
              { "size": "40x40",    "idiom": "iphone",         "filename": "AppIcon-40@2x.png",   "scale": "2x" },
              { "size": "40x40",    "idiom": "iphone",         "filename": "AppIcon-40@3x.png",   "scale": "3x" },
              { "size": "60x60",    "idiom": "iphone",         "filename": "AppIcon-60@2x.png",   "scale": "2x" },
              { "size": "60x60",    "idiom": "iphone",         "filename": "AppIcon-60@3x.png",   "scale": "3x" },
              { "size": "1024x1024","idiom": "ios-marketing",  "filename": "AppIcon-1024.png",    "scale": "1x" }
            ],
            "info": { "version": 1, "author": "xcode" }
          }
          JSON
          echo "Contents.json normalized"

      - name: "Validate Contents json filenames"
        script: |
          set -euxo pipefail
          APPICON_DIR="Assets.xcassets/AppIcon.appiconset"
          JSON="$APPICON_DIR/Contents.json"
          test -s "$JSON"
          python3 - <<'PY'
          import json, os, sys
          base = "Assets.xcassets/AppIcon.appiconset"
          with open(os.path.join(base, "Contents.json")) as f:
              d = json.load(f)
          missing = []
          has_120 = False
          for img in d.get("images", []):
              fn = img.get("filename")
              idiom = img.get("idiom")
              size = img.get("size")
              scale = img.get("scale")
              if fn and not os.path.exists(os.path.join(base, fn)):
                  missing.append(fn)
              if idiom == "iphone" and size == "60x60" and scale == "2x" and fn:
                  has_120 = True
          if missing:
              print("Missing files in Contents.json:", ", ".join(missing)); sys.exit(1)
          if not has_120:
              print("Missing 60x60 @2x iPhone icon reference"); sys.exit(1)
          print("Contents.json looks OK")
          PY

      - name: "Bump version and ensure CFBundleIconName"
        script: |
          set -euxo pipefail
          PLIST="Info.plist"
          /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString 1.1" "$PLIST" || /usr/libexec/PlistBuddy -c "Add :CFBundleShortVersionString string 1.1" "$PLIST"
          BUILD_NUM="$(date +%Y%m%d%H%M)"
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion ${BUILD_NUM}" "$PLIST" || /usr/libexec/PlistBuddy -c "Add :CFBundleVersion string ${BUILD_NUM}" "$PLIST"
          /usr/libexec/PlistBuddy -c "Set :CFBundleIconName AppIcon" "$PLIST" || /usr/libexec/PlistBuddy -c "Add :CFBundleIconName string AppIcon" "$PLIST"

      - name: "Import p12 certificate"
        script: |
          set -euxo pipefail
          keychain initialize
          echo "$P12_BASE64" | base64 --decode > "$CM_BUILD_DIR/AppleDistribution.p12"
          keychain add-certificates --certificate "$CM_BUILD_DIR/AppleDistribution.p12" --certificate-password "$P12_PASSWORD"
          security find-identity -p codesigning -v || true

      - name: "Restore provisioning profile"
        script: |
          set -euxo pipefail
          STD_DIR="$HOME/Library/MobileDevice/Provisioning Profiles"
          mkdir -p "$STD_DIR"
          PROFILE_STD="$STD_DIR/SmartKurv_AppStore.mobileprovision"
          echo "$PROFILE_BASE64" | base64 --decode > "$PROFILE_STD"
          test -s "$PROFILE_STD"
          ls -la "$STD_DIR" || true

      - name: "Configure signing in project"
        script: |
          set -euxo pipefail
          PBX="SmartKurv.xcodeproj/project.pbxproj"
          sed -i '' -e 's/CODE_SIGN_STYLE = Automatic;/CODE_SIGN_STYLE = Manual;/g' "$PBX" || true
          sed -i '' -e 's/PROVISIONING_PROFILE_SPECIFIER = "[^"]*";/PROVISIONING_PROFILE_SPECIFIER = "";/g' "$PBX" || true
          sed -i '' -e 's/PROVISIONING_PROFILE = "[^"]*";/PROVISIONING_PROFILE = "";/g' "$PBX" || true
          xcode-project use-profiles --project SmartKurv.xcodeproj
          xcodebuild -project SmartKurv.xcodeproj -scheme SmartKurv -showBuildSettings | grep -E 'CODE_SIGN_STYLE|DEVELOPMENT_TEAM|PRODUCT_BUNDLE_IDENTIFIER|CODE_SIGN_IDENTITY|PROVISIONING_PROFILE_SPECIFIER' || true

      - name: "Build archive"
        script: |
          set -euxo pipefail
          xcodebuild \
            -project SmartKurv.xcodeproj \
            -scheme SmartKurv \
            -configuration Release \
            -archivePath "$CM_BUILD_DIR/SmartKurv.xcarchive" \
            -sdk iphoneos \
            -allowProvisioningUpdates \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            DEVELOPMENT_TEAM="$TEAM_ID" \
            PRODUCT_BUNDLE_IDENTIFIER="$APP_BUNDLE_ID" \
            ASSETCATALOG_COMPILER_APPICON_NAME=AppIcon \
            ASSETCATALOG_COMPILER_INCLUDE_ALL_APPICON_ASSETS=YES \
            GENERATE_INFOPLIST_FILE=NO \
            archive

      - name: "Fallback compile asset catalog if missing"
        script: |
          set -euxo pipefail
          APP_DIR="$CM_BUILD_DIR/SmartKurv.xcarchive/Products/Applications/SmartKurv.app"
          if [ ! -f "$APP_DIR/Assets.car" ]; then
            echo "Assets.car missing -> compiling Assets.xcassets into app"
            xcrun actool \
              --compile "$APP_DIR" \
              --platform iphoneos \
              --minimum-deployment-target 16.0 \
              --app-icon AppIcon \
              --output-partial-info-plist "$CM_BUILD_DIR/asset-info.plist" \
              Assets.xcassets
            ls -la "$APP_DIR/Assets.car"
          else
            echo "Assets.car already present"
          fi

      - name: "Verify archive icons"
        script: |
          set -euxo pipefail
          APP_DIR="$CM_BUILD_DIR/SmartKurv.xcarchive/Products/Applications/SmartKurv.app"
          APP_PLIST="$APP_DIR/Info.plist"
          /usr/libexec/PlistBuddy -c "Print :CFBundleIconName" "$APP_PLIST" >/dev/null 2>&1 || { echo "Missing CFBundleIconName in archive"; exit 1; }
          test -f "$APP_DIR/Assets.car" || { echo "Assets.car still missing"; exit 1; }

      - name: "Write exportOptions plist"
        script: |
          set -euxo pipefail
          PROFILE_STD="$HOME/Library/MobileDevice/Provisioning Profiles/SmartKurv_AppStore.mobileprovision"
          PROFILE_PLIST="$CM_BUILD_DIR/profile.plist"
          /usr/bin/security cms -D -i "$PROFILE_STD" > "$PROFILE_PLIST"
          PROFILE_NAME=$(/usr/libexec/PlistBuddy -c 'Print :Name' "$PROFILE_PLIST")
          cat > "$CM_BUILD_DIR/exportOptions.plist" << PLIST
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store</string>
            <key>teamID</key><string>$TEAM_ID</string>
            <key>signingStyle</key><string>manual</string>
            <key>signingCertificate</key><string>Apple Distribution</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>$APP_BUNDLE_ID</key>
              <string>$PROFILE_NAME</string>
            </dict>
            <key>uploadSymbols</key><true/>
            <key>compileBitcode</key><false/>
            <key>destination</key><string>export</string>
          </dict>
          </plist>
          PLIST

      - name: "Export ipa"
        script: |
          set -euxo pipefail
          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/SmartKurv.xcarchive" \
            -exportOptionsPlist "$CM_BUILD_DIR/exportOptions.plist" \
            -exportPath "$CM_BUILD_DIR/exported"

      - name: "Upload to TestFlight"
        script: |
          set -euxo pipefail
          IPA="$CM_BUILD_DIR/exported/SmartKurv.ipa"
          test -s "$IPA" || { echo "IPA not found"; exit 1; }
          app-store-connect publish \
            --apple-id "$APPLE_APP_ID" \
            --path "$IPA" \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY"

    artifacts:
      - "$CM_BUILD_DIR/exported/*.ipa"