workflows:
  ios_release:
    name: SmartKurv iOS (TestFlight)
    environment:
      xcode: latest
      groups:
        - appstore_api    # <- den variable-gruppe hvor dine 3 API nøgler ligger
      vars:
        APP_BUNDLE_ID: com.youssef19900.SmartKurv
        TEAM_ID: GUYJ52Y55V
        APPLE_APP_ID: 6753662256  # <- erstat med dit rigtige tal fra App Store Connect

    scripts:
      - name: Install tools
        script: |
          set -euxo pipefail
          brew install xcodegen
          pip3 install --upgrade codemagic-cli-tools

      - name: Generate Xcode project
        script: |
          set -euxo pipefail
          xcodegen generate --spec project.yml

      # 🟢 === LØSNING B START ===
      - name: Create temporary private key for certificate CSR
        script: |
          set -euxo pipefail
          echo "Generating temporary certificate key..."
          openssl genrsa -out "$CM_BUILD_DIR/cert_key.pem" 2048
          test -s "$CM_BUILD_DIR/cert_key.pem"

      - name: Fetch signing files (certificates + profiles)
        script: |
          set -euxo pipefail
          echo "Fetching signing files using Apple API integration..."

          CERT_KEY_CONTENT="$(cat "$CM_BUILD_DIR/cert_key.pem")"

          app-store-connect fetch-signing-files \
            "$APP_BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create \
            --delete-stale-profiles \
            --certificate-key "$CERT_KEY_CONTENT" \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY"
      # 🟢 === LØSNING B SLUT ===

      - name: Import certs & apply profiles to Xcode project
        script: |
          set -euxo pipefail
          keychain initialize
          keychain add-certificates
          xcode-project use-profiles \
            --project SmartKurv.xcodeproj \
            --target SmartKurv

      - name: Build archive (codesigned)
        script: |
          set -euxo pipefail
          xcodebuild \
            -project SmartKurv.xcodeproj \
            -scheme SmartKurv \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/SmartKurv.xcarchive \
            -sdk iphoneos \
            -allowProvisioningUpdates \
            archive

      - name: Write exportOptions.plist (App Store)
        script: |
          set -euxo pipefail
          cat > $CM_BUILD_DIR/exportOptions.plist << 'PLIST'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store</string>
            <key>uploadSymbols</key><true/>
            <key>compileBitcode</key><false/>
            <key>destination</key><string>export</string>
          </dict>
          </plist>
          PLIST

      - name: Export .ipa
        script: |
          set -euxo pipefail
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/SmartKurv.xcarchive \
            -exportOptionsPlist $CM_BUILD_DIR/exportOptions.plist \
            -exportPath $CM_BUILD_DIR/exported

      - name: Publish to TestFlight
        script: |
          set -euxo pipefail
          app-store-connect publish \
            --apple-id "$APPLE_APP_ID" \
            --path "$CM_BUILD_DIR/exported/SmartKurv.ipa"

    artifacts:
      - $CM_BUILD_DIR/exported/*.ipa
