workflows:
  ios_release:
    name: SmartKurv iOS (TestFlight)
    environment:
      xcode: latest
      groups:
        - smartkurv   # Skal indeholde dine certifikater og API-nøgler
      vars:
        APP_BUNDLE_ID: com.youssef19900.SmartKurv
        TEAM_ID: GUYJ52Y55V
        APPLE_APP_ID: "6753662256"
        ICON_SET_PATH: Assets.xcassets/AppIcon.appiconset

    scripts:
      - name: Install tools
        script: |
          set -euxo pipefail
          brew install xcodegen
          pip3 install --upgrade codemagic-cli-tools

      - name: Regenerate project
        script: |
          set -euxo pipefail
          rm -rf SmartKurv.xcodeproj
          xcodegen generate --spec project.yml

      - name: Check assets
        script: |
          set -euxo pipefail
          echo "== Assets folder =="
          ls -la Assets.xcassets || true
          echo "== AppIcon set =="
          ls -la "$ICON_SET_PATH" || true
          echo "Contents.json:"
          cat "$ICON_SET_PATH/Contents.json" || true

      - name: Validate AppIcon sizes
        script: |
          set -euxo pipefail
          cd "$ICON_SET_PATH"
          for f in AppIcon-60@2x.png AppIcon-60@3x.png AppIcon-1024.png; do
            test -f "$f" || { echo "❌ Mangler $f"; exit 1; }
          done
          echo "✅ AppIcons findes alle."

      - name: Force-compile Assets.xcassets (sikrer AppIcon medtages)
        script: |
          set -euxo pipefail
          mkdir -p "$CM_BUILD_DIR/AssetsBuild"
          xcrun actool \
            --compile "$CM_BUILD_DIR/AssetsBuild" \
            --platform iphoneos \
            --minimum-deployment-target 16.0 \
            --app-icon AppIcon \
            Assets.xcassets
          echo "✅ Assets compiled manually to $CM_BUILD_DIR/AssetsBuild"
          ls -la "$CM_BUILD_DIR/AssetsBuild" || true

      - name: Import certificate
        script: |
          set -euxo pipefail
          keychain initialize
          echo "$P12_BASE64" | base64 --decode > "$CM_BUILD_DIR/AppleDistribution.p12"
          keychain add-certificates --certificate "$CM_BUILD_DIR/AppleDistribution.p12" --certificate-password "$P12_PASSWORD"

      - name: Restore provisioning profile
        script: |
          set -euxo pipefail
          mkdir -p "$HOME/Library/MobileDevice/Provisioning Profiles"
          echo "$PROFILE_BASE64" | base64 --decode > "$HOME/Library/MobileDevice/Provisioning Profiles/SmartKurv_AppStore.mobileprovision"

      - name: Bump version and plist sanity
        script: |
          set -euxo pipefail
          PLIST="Info.plist"
          /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString 1.1" "$PLIST" || \
            /usr/libexec/PlistBuddy -c "Add :CFBundleShortVersionString string 1.1" "$PLIST"
          BUILD_NUM="$(date +%Y%m%d%H%M)"
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion ${BUILD_NUM}" "$PLIST" || \
            /usr/libexec/PlistBuddy -c "Add :CFBundleVersion string ${BUILD_NUM}" "$PLIST"
          /usr/libexec/PlistBuddy -c "Set :CFBundleIconName AppIcon" "$PLIST" || \
            /usr/libexec/PlistBuddy -c "Add :CFBundleIconName string AppIcon" "$PLIST"

      - name: Build archive
        script: |
          set -euxo pipefail
          xcodebuild \
            -project SmartKurv.xcodeproj \
            -scheme SmartKurv \
            -configuration Release \
            -archivePath "$CM_BUILD_DIR/SmartKurv.xcarchive" \
            -sdk iphoneos \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            DEVELOPMENT_TEAM="$TEAM_ID" \
            archive

      - name: Inspect archive
        script: |
          set -euxo pipefail
          APP_PATH="$CM_BUILD_DIR/SmartKurv.xcarchive/Products/Applications/SmartKurv.app"
          echo "== App contents =="
          ls -la "$APP_PATH" || true
          if [ -f "$APP_PATH/Assets.car" ]; then
            echo "✅ Assets.car findes!"
          else
            echo "❌ Assets.car mangler - tjek assets-path i project.yml"
          fi

      - name: Export ipa
        script: |
          set -euxo pipefail
          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/SmartKurv.xcarchive" \
            -exportPath "$CM_BUILD_DIR/exported" \
            -exportOptionsPlist <(cat << PLIST
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store</string>
            <key>teamID</key><string>$TEAM_ID</string>
            <key>uploadSymbols</key><true/>
            <key>compileBitcode</key><false/>
          </dict>
          </plist>
          PLIST)

      - name: Upload to TestFlight
        script: |
          set -euxo pipefail
          app-store-connect publish \
            --apple-id "$APPLE_APP_ID" \
            --path "$CM_BUILD_DIR/exported/SmartKurv.ipa"

    artifacts:
      - "$CM_BUILD_DIR/exported/*.ipa"
