name: SmartKurv
options:
  minimumXcodeGenVersion: 2.37.0

targets:
  SmartKurv:
    type: application
    platform: iOS
    deploymentTarget: "16.0"

    # Kildemappe
    sources:
      - path: .
        excludes:
          - project.yml
          - codemagic.yaml
          - README.md

    # Ressourcer (så catalog.json og evt. assets kommer med i appen)
    resources:
      - path: Assets.xcassets
      - path: catalog.json

    settings:
      base:
        SWIFT_VERSION: 5.0
        CODE_SIGN_STYLE: Manual
        DEVELOPMENT_TEAM: ""
        PRODUCT_BUNDLE_IDENTIFIER: com.youssef19900.SmartKurv
        INFOPLIST_FILE: Info.plist

    scheme:
      testTargets: []
