name: SmartKurv
options:
  minimumXcodeGenVersion: 2.37.0

targets:
  SmartKurv:
    type: application
    platform: iOS
    deploymentTarget: "16.0"

    # Kode
    sources:
      - path: .
        excludes:
          - project.yml
          - codemagic.yaml
          - README.md

    # Ressourcer
    resources:
      - path: Assets.xcassets
      - path: catalog.json

    # Plist
    info:
      path: Info.plist

    settings:
      base:
        SWIFT_VERSION: 5.0
        CODE_SIGN_STYLE: Manual
        DEVELOPMENT_TEAM: GUYJ52Y55V         # ← dit Team ID
        PRODUCT_BUNDLE_IDENTIFIER: com.youssef19900.SmartKurv

    scheme:
      testTargets: []
