name: SmartKurv
options:
  minimumXcodeGenVersion: 2.37.0

targets:
  SmartKurv:
    type: application
    platform: iOS
    deploymentTarget: "16.0"

    sources:
      - path: SmartKurv
        optional: false
      - path: UI
        optional: false
      - path: Location
        optional: true
      - path: .
        optional: true
        includes:
          - Theme.swift
          - SmartKurvApp.swift

    resources:
      - path: Assets.xcassets
        optional: false
      - LaunchScreen.storyboard
      - path: Resources
        optional: true
        includes:
          - "*.json"
          - "*.csv"

    info:
      path: Info.plist

    settings:
      base:
        INFOPLIST_FILE: Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.youssef19900.SmartKurv
        DEVELOPMENT_TEAM: GUYJ52Y55V
        CODE_SIGN_STYLE: Manual
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        INFOPLIST_KEY_CFBundleIconName: AppIcon
        INFOPLIST_KEY_UIUserInterfaceStyle: Dark
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: "1"

      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"

    scheme:
      name: SmartKurv
      testTargets: []
