name: SmartKurv
options:
  minimumXcodeGenVersion: 2.37.0

targets:
  SmartKurv:
    type: application
    platform: iOS
    deploymentTarget: "16.0"

    # Kildemapper
    sources:
      - path: Smartkurv         # <- her ligger AppState.swift, Models.swift, PricingService.swift, CatalogService.swift
        optional: true
      - path: UI
        optional: true
      - path: Location
        optional: true
      - path: .
        excludes:
          - project.yml
          - codemagic.yaml
          - README.md
          - .git
          - .github
          - Assets.xcassets
          - LaunchScreen.storyboard
          - Resources

    # Ressourcer (kopieres til app-bundlen)
    resources:
      - Assets.xcassets
      - LaunchScreen.storyboard
      - path: Resources
        optional: true
        includes:

    info:
      path: Info.plist

    settings:
      base:
        SWIFT_VERSION: 5.0
        PRODUCT_BUNDLE_IDENTIFIER: com.youssef19900.SmartKurv
        DEVELOPMENT_TEAM: GUYJ52Y55V

        # Codesigning (Codemagic "use-profiles" sætter profilerne)
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: "Apple Distribution"
        CODE_SIGN_IDENTITY[sdk=iphoneos*]: "Apple Distribution"
        PROVISIONING_PROFILE_SPECIFIER: ""
        PROVISIONING_PROFILE: ""

        # App icon
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon

        # iPhone only
        TARGETED_DEVICE_FAMILY: "1"

        # Versions
        MARKETING_VERSION: 1.0
        CURRENT_PROJECT_VERSION: 1

        # (valgfrit) tving mørkt UI via Info.plist key
        INFOPLIST_KEY_UIUserInterfaceStyle: Dark

      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"

    scheme:
      name: SmartKurv
      testTargets: []
