name: SmartKurv
options:
  minimumXcodeGenVersion: 2.37.0

targets:
  SmartKurv:
    type: application
    platform: iOS
    deploymentTarget: "16.0"

    sources:
      - path: .
        excludes:
          - project.yml
          - codemagic.yaml
          - README.md
          - .git
          - .github

    resources:
      - Assets.xcassets
      - catalog.json

    info:
      path: Info.plist

    settings:
      base:
        SWIFT_VERSION: 5.0
        PRODUCT_BUNDLE_IDENTIFIER: com.youssef19900.SmartKurv
        DEVELOPMENT_TEAM: GUYJ52Y55V
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: "Apple Distribution"             # <- generisk, ikke personnavn
        CODE_SIGN_IDENTITY[sdk=iphoneos*]: "Apple Distribution"
        PROVISIONING_PROFILE_SPECIFIER: ""                   # <- tom; sættes af use-profiles
        PROVISIONING_PROFILE: ""                             # <- tom; sættes af use-profiles

    scheme:
      name: SmartKurv
      testTargets: []
