name: SmartKurv
options:
  minimumXcodeGenVersion: 2.37.0

targets:
  SmartKurv:
    type: application
    platform: iOS
    deploymentTarget: "16.0"

    # Kildemapper der bygges
    sources:
      - path: SmartKurv          # AppState, Models, PricingService, CatalogService
        optional: false
      - path: UI                 # Views, tabs, UI-komponenter
        optional: false
      - path: Location           # LocationManager
        optional: true
      # Filer i roden som også skal med
      - path: .
        optional: true
        includes:
          - Theme.swift
          - SmartKurvApp.swift

    # Assets og øvrige ressourcer
    resources:
      - Assets.xcassets
      - LaunchScreen.storyboard
      - path: Resources
        optional: true
        includes:
          - "*.json"
          - "*.csv"

    # Info.plist der skal bruges
    info:
      path: Info.plist

    settings:
      base:
        # Sikr at Xcode bruger denne plist (ud over 'info.path' ovenfor)
        INFOPLIST_FILE: Info.plist

        # App icon setup
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        INFOPLIST_KEY_CFBundleIconName: AppIcon

        # Generelle settings
        SWIFT_VERSION: 5.0
        PRODUCT_BUNDLE_IDENTIFIER: com.youssef19900.SmartKurv
        DEVELOPMENT_TEAM: GUYJ52Y55V
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: "Apple Distribution"
        CODE_SIGN_IDENTITY[sdk=iphoneos*]: "Apple Distribution"
        PROVISIONING_PROFILE_SPECIFIER: ""
        PROVISIONING_PROFILE: ""
        TARGETED_DEVICE_FAMILY: "1"
        MARKETING_VERSION: 1.1
        CURRENT_PROJECT_VERSION: 1
        INFOPLIST_KEY_UIUserInterfaceStyle: Dark

      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"

    scheme:
      name: SmartKurv
      testTargets: []
