name: SmartKurv
options:
  minimumXcodeGenVersion: 2.37.0

targets:
  SmartKurv:
    type: application
    platform: iOS
    deploymentTarget: "16.0"

    sources:
      - path: .
        excludes:
          - project.yml
          - codemagic.yaml
          - README.md
          - .git
          - .github

    resources:
      - Assets.xcassets
      - catalog.json
      - LaunchScreen.storyboard   # ← tilføjet launch screen

    info:
      path: Info.plist

    settings:
      base:
        SWIFT_VERSION: 5.0
        PRODUCT_BUNDLE_IDENTIFIER: com.youssef19900.SmartKurv
        DEVELOPMENT_TEAM: GUYJ52Y55V

        # Codesigning styres manuelt (Codemagic "use-profiles" sætter profilerne)
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: "Apple Distribution"
        CODE_SIGN_IDENTITY[sdk=iphoneos*]: "Apple Distribution"
        PROVISIONING_PROFILE_SPECIFIER: ""   # tom; sættes af use-profiles
        PROVISIONING_PROFILE: ""             # tom; sættes af use-profiles

        # App icon set navn (skal matche Assets.xcassets/AppIcon.appiconset)
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon

        # iPhone-only (undgår iPad multitasking/launchscreen-krav)
        TARGETED_DEVICE_FAMILY: "1"

        # (valgfrit) versionsfelter – kan også styres i Info.plist
        MARKETING_VERSION: 1.0
        CURRENT_PROJECT_VERSION: 1

    scheme:
      name: SmartKurv
      testTargets: []
